---
name: libblkid nightly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 5 3 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  allowed_failures:
    continue-on-error: true
    strategy:
      matrix:
        include:
          # Run "cargo audit" on rust stable. Make it an allowed failure. It
          # should be an advisory and should not gate our development.
          - components: cargo
            toolchain: stable
            task: audit
          # Allowed because a failure may occur after a new Rust stable
          # version is released.
          - components: clippy
            toolchain: stable
            task: clippy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: ${{ matrix.components }}
          toolchain: ${{ matrix.toolchain }}
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libblkid-dev
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: make -f Makefile ${{ matrix.task }}

  checks-with-ci-repo:
    runs-on: ubuntu-20.04
    container:
      image: fedora:40  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          curl
          git
          libblkid-devel
          make
          openssl-devel
          python-requests
          python-semantic_version
      - uses: dtolnay/rust-toolchain@master
        with:
          components: cargo
          toolchain: 1.82.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
      - name: Check out ci repo
        run: git clone https://github.com/stratis-storage/ci.git
      - name: Run comparisons of version specs with available Fedora packages
        # yamllint disable rule:line-length
        run: |
          # -sys
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../libblkid-rs-sys/Cargo.toml FEDORA_RELEASE=rawhide make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../libblkid-rs-sys/Cargo.toml FEDORA_RELEASE=f40 make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../libblkid-rs-sys/Cargo.toml FEDORA_RELEASE=f39 make -f ../../Makefile check-fedora-versions
          # main
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=rawhide make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=f40 make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=f39 make -f ../../Makefile check-fedora-versions
        working-directory: ./ci/dependency_management

  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libblkid-dev
      - name: Do semantic version checks
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          verbose: true
          rust-toolchain: 1.82.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
